# Example Configuration for View Default Tab KNUTS

## Basic Configuration

```yaml
view_default_tab:
  users:
    - username: "john"
      default_tab: 1
    - username: "mary"
      default_tab: 2
```

## Real-world Dashboard Integration

Here's how to integrate it into your existing dashboard configuration:

```yaml
view_default_tab:
  users:
    - username: "parent1"
      default_tab: 0  # Master bedroom tab
    - username: "parent2"
      default_tab: 0  # Master bedroom tab  
    - username: "tibe"
      default_tab: 1  # Tibe's room tab
    - username: "menthe"
      default_tab: 2  # Menthe's room tab
    - username: "guest"
      default_tab: 0  # Default to Master for guests

views:
  - title: Master
    sections:
      - type: grid
        cards:
          - type: heading
            icon: mdi:lightbulb
            heading: Lights
            heading_style: subtitle
          # ... your existing cards
        column_span: 1
    type: sections
    max_columns: 4
    cards: []
    icon: mdi:bed-double-outline
  - title: Tibe
    sections:
      # Your Tibe room configuration
    type: sections
    max_columns: 4
    cards: []
    icon: mdi:bed
  - title: Menthe
    sections:
      # Your Menthe room configuration  
    type: sections
    max_columns: 4
    cards: []
    icon: mdi:bed
```

## Configuration Options

### Required
- `users`: Array of user configurations
  - `username`: Home Assistant username (string)
  - `default_tab`: Tab index to redirect to (number, 0-based)

## Tab Index Reference

For your bedroom dashboard:
- `0` = Master (first tab)
- `1` = Tibe (second tab) 
- `2` = Menthe (third tab)

## Integration Notes

- Add the configuration at the **top level** of your dashboard YAML
- Similar to how `keep_texts_in_tabs` works
- Don't modify your existing views
- Each family member gets redirected to their bedroom automatically
- Users can still manually navigate to any room after initial redirect